### ISSUE TITLE
Can't create issue for forked MM repo - what is the Cloudron user password for Mattermost CLI?

### ISSUE THREAD

**Issue by ra-uk** [cloudron-io/Where-to-start#1]
Hello,

I've been googling for ages and am trying to delete a team.

there isn't much on the cloudron website and when I try to delete the team I get asked for the Cloudron user password

(after adding the user with this: `sudo -u cloudron /app/code/bin/platform --config=/app/data/config.json help` )

I tried to change the password with passwd but it gives me some error about "Authentication token manipulation error"

What is the preset password for the Cloudron user for the Mattermost CLI, please!?

**Comment by nebulade** [comment]
There is no preset password or account, Mattermost will ask you to setup the admin user upon first login. So maybe you can try the first user who was created.
